services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    env_file:
      - .env
    networks:
      - internal
  redis:
    image: redis:7.4-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
    networks:
      - internal
  server:
    image: caddy:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - web
      - internal
volumes:
  cache:

networks:
  web:
    external: true
  internal:
    external: false
    driver: bridge

